# Dockerfile.backend

FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# Копируем requirements
COPY backend/requirements.txt /app/

RUN pip install --upgrade pip && pip install -r requirements.txt

# Копируем весь backend внутрь контейнера
COPY backend/projecta_backend/ /app/

# Собираем
RUN python manage.py collectstatic --noinput || true

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
